# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

call_hash <- function(s) {
    .Call('Resonance_call_hash', PACKAGE = 'Resonance', s)
}

prepareMvFFT <- function(rows, columns) {
    .Call('Resonance_prepareMvFFT', PACKAGE = 'Resonance', rows, columns)
}

performMvFFT <- function(xpc, data) {
    .Call('Resonance_performMvFFT', PACKAGE = 'Resonance', xpc, data)
}

forceCopy <- function(m) {
    .Call('Resonance_forceCopy', PACKAGE = 'Resonance', m)
}

shiftRows <- function(m, shift) {
    invisible(.Call('Resonance_shiftRows', PACKAGE = 'Resonance', m, shift))
}

pushRows_bottom <- function(m, p) {
    invisible(.Call('Resonance_pushRows_bottom', PACKAGE = 'Resonance', m, p))
}

pushRows_top <- function(m, p) {
    invisible(.Call('Resonance_pushRows_top', PACKAGE = 'Resonance', m, p))
}

push_slice_rows_back <- function(dest, src, slicePos, sliceSize) {
    invisible(.Call('Resonance_push_slice_rows_back', PACKAGE = 'Resonance', dest, src, slicePos, sliceSize))
}

rowsCopy <- function(dest, destBegin, src, srcBegin, srcSize) {
    invisible(.Call('Resonance_rowsCopy', PACKAGE = 'Resonance', dest, destBegin, src, srcBegin, srcSize))
}

replace_columns_block <- function(m, destRow, destCol, src) {
    invisible(.Call('Resonance_replace_columns_block', PACKAGE = 'Resonance', m, destRow, destCol, src))
}

copyColumns <- function(dest, src, cols) {
    invisible(.Call('Resonance_copyColumns', PACKAGE = 'Resonance', dest, src, cols))
}

